version: 2
jobs:
  build:
    working_directory: ~/konserve-firebase
    docker:
      - image: openjdk:8
    environment:
      LEIN_ROOT=nbd
    steps:
      - checkout
      - restore_cache:
          key: {{ checksum "project.clj" }}
      - run: apt update && apt install -qy phantomjs
      - run: bin/lein deps
      - save_cache:
          paths:
            - ~/.m2
            - ~/.lein
          key: {{ checksum "project.clj" }}
    test:
      - run: bin/lein do phantom once test, jar, deploy clojars
