version: 2
jobs:
  build:
    working_directory: ~/konserve-firebase
    environment:
      - JVM_OPTS=-Xmx3500m
    docker:
      - image: lsenta/cljs-testing:latest
    steps:
      - checkout
      - restore_cache:
          key: << checksum "project.clj" >>
      - run: lein with-profile +test deps
      - save_cache:
          paths:
            - ~/.m2
            - ~/.lein
          key: << checksum "project.clj" >>
      - run: lein test
      - run: lein doo phantom once test
      - run: lein jar
      - run: lein deploy
