version: 2
jobs:
  build:
    working_directory: ~/konserve-firebase
    docker:
      - image: lsenta/cljs-testing:latest
    steps:
      - checkout
      - restore_cache:
          key: << checksum "project.clj" >>
      - run: bin/lein with-profile +test deps
      - save_cache:
          paths:
            - ~/.m2
            - ~/.lein
          key: << checksum "project.clj" >>
      - run: bin/lein test
      - run: bin/lein doo phantom once test
      - run: bin/lein jar
      - run: bin/lein deploy
